// Generated by gencpp from file mir_actions/RelativeMoveGoal.msg
// DO NOT EDIT!


#ifndef MIR_ACTIONS_MESSAGE_RELATIVEMOVEGOAL_H
#define MIR_ACTIONS_MESSAGE_RELATIVEMOVEGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace mir_actions
{
template <class ContainerAllocator>
struct RelativeMoveGoal_
{
  typedef RelativeMoveGoal_<ContainerAllocator> Type;

  RelativeMoveGoal_()
    : target_pose()
    , yaw(0.0)
    , collision_detection(false)
    , disable_collision_check_dist(0.0)
    , max_linear_speed(0.0)
    , max_rotational_speed(0.0)
    , pid_dist_offset(0.0)
    , target_offset(0.0)
    , only_collision_detection(false)
    , timeout(0.0)
    , same_goal(false)  {
    }
  RelativeMoveGoal_(const ContainerAllocator& _alloc)
    : target_pose(_alloc)
    , yaw(0.0)
    , collision_detection(false)
    , disable_collision_check_dist(0.0)
    , max_linear_speed(0.0)
    , max_rotational_speed(0.0)
    , pid_dist_offset(0.0)
    , target_offset(0.0)
    , only_collision_detection(false)
    , timeout(0.0)
    , same_goal(false)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _target_pose_type;
  _target_pose_type target_pose;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef uint8_t _collision_detection_type;
  _collision_detection_type collision_detection;

   typedef double _disable_collision_check_dist_type;
  _disable_collision_check_dist_type disable_collision_check_dist;

   typedef double _max_linear_speed_type;
  _max_linear_speed_type max_linear_speed;

   typedef double _max_rotational_speed_type;
  _max_rotational_speed_type max_rotational_speed;

   typedef double _pid_dist_offset_type;
  _pid_dist_offset_type pid_dist_offset;

   typedef double _target_offset_type;
  _target_offset_type target_offset;

   typedef uint8_t _only_collision_detection_type;
  _only_collision_detection_type only_collision_detection;

   typedef double _timeout_type;
  _timeout_type timeout;

   typedef uint8_t _same_goal_type;
  _same_goal_type same_goal;





  typedef boost::shared_ptr< ::mir_actions::RelativeMoveGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mir_actions::RelativeMoveGoal_<ContainerAllocator> const> ConstPtr;

}; // struct RelativeMoveGoal_

typedef ::mir_actions::RelativeMoveGoal_<std::allocator<void> > RelativeMoveGoal;

typedef boost::shared_ptr< ::mir_actions::RelativeMoveGoal > RelativeMoveGoalPtr;
typedef boost::shared_ptr< ::mir_actions::RelativeMoveGoal const> RelativeMoveGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mir_actions::RelativeMoveGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mir_actions::RelativeMoveGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mir_actions

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'mir_actions': ['/home/ros/MiR_ws/devel/share/mir_actions/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mir_actions::RelativeMoveGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mir_actions::RelativeMoveGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mir_actions::RelativeMoveGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mir_actions::RelativeMoveGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mir_actions::RelativeMoveGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mir_actions::RelativeMoveGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mir_actions::RelativeMoveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ceef9ff5cf266b0a2f52eea13fa5ba8a";
  }

  static const char* value(const ::mir_actions::RelativeMoveGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xceef9ff5cf266b0aULL;
  static const uint64_t static_value2 = 0x2f52eea13fa5ba8aULL;
};

template<class ContainerAllocator>
struct DataType< ::mir_actions::RelativeMoveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mir_actions/RelativeMoveGoal";
  }

  static const char* value(const ::mir_actions::RelativeMoveGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mir_actions::RelativeMoveGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
geometry_msgs/PoseStamped target_pose\n\
float64 yaw\n\
bool collision_detection\n\
float64 disable_collision_check_dist\n\
float64 max_linear_speed\n\
float64 max_rotational_speed\n\
float64 pid_dist_offset\n\
float64 target_offset\n\
bool only_collision_detection\n\
float64 timeout\n\
bool same_goal\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::mir_actions::RelativeMoveGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mir_actions::RelativeMoveGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_pose);
      stream.next(m.yaw);
      stream.next(m.collision_detection);
      stream.next(m.disable_collision_check_dist);
      stream.next(m.max_linear_speed);
      stream.next(m.max_rotational_speed);
      stream.next(m.pid_dist_offset);
      stream.next(m.target_offset);
      stream.next(m.only_collision_detection);
      stream.next(m.timeout);
      stream.next(m.same_goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RelativeMoveGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mir_actions::RelativeMoveGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mir_actions::RelativeMoveGoal_<ContainerAllocator>& v)
  {
    s << indent << "target_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.target_pose);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "collision_detection: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.collision_detection);
    s << indent << "disable_collision_check_dist: ";
    Printer<double>::stream(s, indent + "  ", v.disable_collision_check_dist);
    s << indent << "max_linear_speed: ";
    Printer<double>::stream(s, indent + "  ", v.max_linear_speed);
    s << indent << "max_rotational_speed: ";
    Printer<double>::stream(s, indent + "  ", v.max_rotational_speed);
    s << indent << "pid_dist_offset: ";
    Printer<double>::stream(s, indent + "  ", v.pid_dist_offset);
    s << indent << "target_offset: ";
    Printer<double>::stream(s, indent + "  ", v.target_offset);
    s << indent << "only_collision_detection: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.only_collision_detection);
    s << indent << "timeout: ";
    Printer<double>::stream(s, indent + "  ", v.timeout);
    s << indent << "same_goal: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.same_goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIR_ACTIONS_MESSAGE_RELATIVEMOVEGOAL_H
