// Generated by gencpp from file sdc21x0/Flags.msg
// DO NOT EDIT!


#ifndef SDC21X0_MESSAGE_FLAGS_H
#define SDC21X0_MESSAGE_FLAGS_H

#include <ros/service_traits.h>


#include <sdc21x0/FlagsRequest.h>
#include <sdc21x0/FlagsResponse.h>


namespace sdc21x0
{

struct Flags
{

typedef FlagsRequest Request;
typedef FlagsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Flags
} // namespace sdc21x0


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sdc21x0::Flags > {
  static const char* value()
  {
    return "9eda35869d1a72f6c996c2043f7b4423";
  }

  static const char* value(const ::sdc21x0::Flags&) { return value(); }
};

template<>
struct DataType< ::sdc21x0::Flags > {
  static const char* value()
  {
    return "sdc21x0/Flags";
  }

  static const char* value(const ::sdc21x0::Flags&) { return value(); }
};


// service_traits::MD5Sum< ::sdc21x0::FlagsRequest> should match 
// service_traits::MD5Sum< ::sdc21x0::Flags > 
template<>
struct MD5Sum< ::sdc21x0::FlagsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sdc21x0::Flags >::value();
  }
  static const char* value(const ::sdc21x0::FlagsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sdc21x0::FlagsRequest> should match 
// service_traits::DataType< ::sdc21x0::Flags > 
template<>
struct DataType< ::sdc21x0::FlagsRequest>
{
  static const char* value()
  {
    return DataType< ::sdc21x0::Flags >::value();
  }
  static const char* value(const ::sdc21x0::FlagsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sdc21x0::FlagsResponse> should match 
// service_traits::MD5Sum< ::sdc21x0::Flags > 
template<>
struct MD5Sum< ::sdc21x0::FlagsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sdc21x0::Flags >::value();
  }
  static const char* value(const ::sdc21x0::FlagsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sdc21x0::FlagsResponse> should match 
// service_traits::DataType< ::sdc21x0::Flags > 
template<>
struct DataType< ::sdc21x0::FlagsResponse>
{
  static const char* value()
  {
    return DataType< ::sdc21x0::Flags >::value();
  }
  static const char* value(const ::sdc21x0::FlagsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SDC21X0_MESSAGE_FLAGS_H
