// Generated by gencpp from file sdc21x0/MotorCurrents.msg
// DO NOT EDIT!


#ifndef SDC21X0_MESSAGE_MOTORCURRENTS_H
#define SDC21X0_MESSAGE_MOTORCURRENTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sdc21x0
{
template <class ContainerAllocator>
struct MotorCurrents_
{
  typedef MotorCurrents_<ContainerAllocator> Type;

  MotorCurrents_()
    : left_motor(0.0)
    , right_motor(0.0)  {
    }
  MotorCurrents_(const ContainerAllocator& _alloc)
    : left_motor(0.0)
    , right_motor(0.0)  {
  (void)_alloc;
    }



   typedef float _left_motor_type;
  _left_motor_type left_motor;

   typedef float _right_motor_type;
  _right_motor_type right_motor;





  typedef boost::shared_ptr< ::sdc21x0::MotorCurrents_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sdc21x0::MotorCurrents_<ContainerAllocator> const> ConstPtr;

}; // struct MotorCurrents_

typedef ::sdc21x0::MotorCurrents_<std::allocator<void> > MotorCurrents;

typedef boost::shared_ptr< ::sdc21x0::MotorCurrents > MotorCurrentsPtr;
typedef boost::shared_ptr< ::sdc21x0::MotorCurrents const> MotorCurrentsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sdc21x0::MotorCurrents_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sdc21x0::MotorCurrents_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sdc21x0

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sdc21x0': ['/home/ros/MiR_ws/src/mir_robot/sdc21x0/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sdc21x0::MotorCurrents_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdc21x0::MotorCurrents_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sdc21x0::MotorCurrents_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sdc21x0::MotorCurrents_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdc21x0::MotorCurrents_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdc21x0::MotorCurrents_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sdc21x0::MotorCurrents_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3e3717ac8e9443aa62d7102a5860f5e7";
  }

  static const char* value(const ::sdc21x0::MotorCurrents_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3e3717ac8e9443aaULL;
  static const uint64_t static_value2 = 0x62d7102a5860f5e7ULL;
};

template<class ContainerAllocator>
struct DataType< ::sdc21x0::MotorCurrents_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sdc21x0/MotorCurrents";
  }

  static const char* value(const ::sdc21x0::MotorCurrents_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sdc21x0::MotorCurrents_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 left_motor\n\
float32 right_motor\n\
";
  }

  static const char* value(const ::sdc21x0::MotorCurrents_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sdc21x0::MotorCurrents_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_motor);
      stream.next(m.right_motor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorCurrents_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sdc21x0::MotorCurrents_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sdc21x0::MotorCurrents_<ContainerAllocator>& v)
  {
    s << indent << "left_motor: ";
    Printer<float>::stream(s, indent + "  ", v.left_motor);
    s << indent << "right_motor: ";
    Printer<float>::stream(s, indent + "  ", v.right_motor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SDC21X0_MESSAGE_MOTORCURRENTS_H
