(cl:defpackage people_msgs-msg
  (:use )
  (:export
   "<PEOPLE>"
   "PEOPLE"
   "<PERSON>"
   "PERSON"
   "<PERSONSTAMPED>"
   "PERSONSTAMPED"
   "<POSITIONMEASUREMENT>"
   "POSITIONMEASUREMENT"
   "<POSITIONMEASUREMENTARRAY>"
   "POSITIONMEASUREMENTARRAY"
  ))

