// Generated by gencpp from file mir_msgs/BrakeState.msg
// DO NOT EDIT!


#ifndef MIR_MSGS_MESSAGE_BRAKESTATE_H
#define MIR_MSGS_MESSAGE_BRAKESTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mir_msgs
{
template <class ContainerAllocator>
struct BrakeState_
{
  typedef BrakeState_<ContainerAllocator> Type;

  BrakeState_()
    : state_string()
    , state(0)
    , braked(false)  {
    }
  BrakeState_(const ContainerAllocator& _alloc)
    : state_string(_alloc)
    , state(0)
    , braked(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _state_string_type;
  _state_string_type state_string;

   typedef uint8_t _state_type;
  _state_type state;

   typedef uint8_t _braked_type;
  _braked_type braked;





  typedef boost::shared_ptr< ::mir_msgs::BrakeState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mir_msgs::BrakeState_<ContainerAllocator> const> ConstPtr;

}; // struct BrakeState_

typedef ::mir_msgs::BrakeState_<std::allocator<void> > BrakeState;

typedef boost::shared_ptr< ::mir_msgs::BrakeState > BrakeStatePtr;
typedef boost::shared_ptr< ::mir_msgs::BrakeState const> BrakeStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mir_msgs::BrakeState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mir_msgs::BrakeState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mir_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'mir_msgs': ['/home/ros/MiR_ws/src/mir_robot/mir_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mir_msgs::BrakeState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mir_msgs::BrakeState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mir_msgs::BrakeState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mir_msgs::BrakeState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mir_msgs::BrakeState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mir_msgs::BrakeState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mir_msgs::BrakeState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef848bae4fc67617e079b91594ce733b";
  }

  static const char* value(const ::mir_msgs::BrakeState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef848bae4fc67617ULL;
  static const uint64_t static_value2 = 0xe079b91594ce733bULL;
};

template<class ContainerAllocator>
struct DataType< ::mir_msgs::BrakeState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mir_msgs/BrakeState";
  }

  static const char* value(const ::mir_msgs::BrakeState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mir_msgs::BrakeState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string state_string\n\
uint8 state\n\
bool braked\n\
";
  }

  static const char* value(const ::mir_msgs::BrakeState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mir_msgs::BrakeState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state_string);
      stream.next(m.state);
      stream.next(m.braked);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BrakeState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mir_msgs::BrakeState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mir_msgs::BrakeState_<ContainerAllocator>& v)
  {
    s << indent << "state_string: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.state_string);
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
    s << indent << "braked: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.braked);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIR_MSGS_MESSAGE_BRAKESTATE_H
