// Generated by gencpp from file mir_msgs/Devices.msg
// DO NOT EDIT!


#ifndef MIR_MSGS_MESSAGE_DEVICES_H
#define MIR_MSGS_MESSAGE_DEVICES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mir_msgs/Device.h>

namespace mir_msgs
{
template <class ContainerAllocator>
struct Devices_
{
  typedef Devices_<ContainerAllocator> Type;

  Devices_()
    : devices()  {
    }
  Devices_(const ContainerAllocator& _alloc)
    : devices(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::mir_msgs::Device_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::mir_msgs::Device_<ContainerAllocator> >::other >  _devices_type;
  _devices_type devices;





  typedef boost::shared_ptr< ::mir_msgs::Devices_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mir_msgs::Devices_<ContainerAllocator> const> ConstPtr;

}; // struct Devices_

typedef ::mir_msgs::Devices_<std::allocator<void> > Devices;

typedef boost::shared_ptr< ::mir_msgs::Devices > DevicesPtr;
typedef boost::shared_ptr< ::mir_msgs::Devices const> DevicesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mir_msgs::Devices_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mir_msgs::Devices_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mir_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'mir_msgs': ['/home/ros/MiR_ws/src/mir_robot/mir_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mir_msgs::Devices_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mir_msgs::Devices_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mir_msgs::Devices_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mir_msgs::Devices_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mir_msgs::Devices_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mir_msgs::Devices_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mir_msgs::Devices_<ContainerAllocator> >
{
  static const char* value()
  {
    return "511b1be8e995256c8e1402bcafc15e2b";
  }

  static const char* value(const ::mir_msgs::Devices_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x511b1be8e995256cULL;
  static const uint64_t static_value2 = 0x8e1402bcafc15e2bULL;
};

template<class ContainerAllocator>
struct DataType< ::mir_msgs::Devices_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mir_msgs/Devices";
  }

  static const char* value(const ::mir_msgs::Devices_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mir_msgs::Devices_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mir_msgs/Device[] devices\n\
\n\
================================================================================\n\
MSG: mir_msgs/Device\n\
string name\n\
string serial\n\
";
  }

  static const char* value(const ::mir_msgs::Devices_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mir_msgs::Devices_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.devices);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Devices_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mir_msgs::Devices_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mir_msgs::Devices_<ContainerAllocator>& v)
  {
    s << indent << "devices[]" << std::endl;
    for (size_t i = 0; i < v.devices.size(); ++i)
    {
      s << indent << "  devices[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::mir_msgs::Device_<ContainerAllocator> >::stream(s, indent + "    ", v.devices[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIR_MSGS_MESSAGE_DEVICES_H
