// Generated by gencpp from file mir_msgs/Events.msg
// DO NOT EDIT!


#ifndef MIR_MSGS_MESSAGE_EVENTS_H
#define MIR_MSGS_MESSAGE_EVENTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <mir_msgs/Event.h>

namespace mir_msgs
{
template <class ContainerAllocator>
struct Events_
{
  typedef Events_<ContainerAllocator> Type;

  Events_()
    : header()
    , events()  {
    }
  Events_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , events(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::mir_msgs::Event_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::mir_msgs::Event_<ContainerAllocator> >::other >  _events_type;
  _events_type events;





  typedef boost::shared_ptr< ::mir_msgs::Events_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mir_msgs::Events_<ContainerAllocator> const> ConstPtr;

}; // struct Events_

typedef ::mir_msgs::Events_<std::allocator<void> > Events;

typedef boost::shared_ptr< ::mir_msgs::Events > EventsPtr;
typedef boost::shared_ptr< ::mir_msgs::Events const> EventsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mir_msgs::Events_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mir_msgs::Events_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mir_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'mir_msgs': ['/home/ros/MiR_ws/src/mir_robot/mir_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mir_msgs::Events_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mir_msgs::Events_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mir_msgs::Events_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mir_msgs::Events_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mir_msgs::Events_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mir_msgs::Events_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mir_msgs::Events_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7bc39c0a4512602f564b326a79461af0";
  }

  static const char* value(const ::mir_msgs::Events_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7bc39c0a4512602fULL;
  static const uint64_t static_value2 = 0x564b326a79461af0ULL;
};

template<class ContainerAllocator>
struct DataType< ::mir_msgs::Events_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mir_msgs/Events";
  }

  static const char* value(const ::mir_msgs::Events_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mir_msgs::Events_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
Event[] events\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: mir_msgs/Event\n\
uint32 EV_SPEED=1\n\
uint32 EV_BLINK=2\n\
uint32 EV_SOUND=3\n\
uint32 EV_DOOR=4\n\
uint32 EV_AMCLOFF=5\n\
uint32 EV_FWDDIST=6\n\
uint32 EV_IO=7\n\
uint32 EV_FLEETLCK=8	# Fleet\n\
uint32 EV_EMERGENCY=9	# Fleet\n\
uint32 eventType	# The area event type\n\
string area_guid	# The area unique identifier\n\
string area_name	# The name of the area\n\
geometry_msgs/Point[] polygon # An array of corner points that define the edges of the area\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::mir_msgs::Events_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mir_msgs::Events_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.events);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Events_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mir_msgs::Events_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mir_msgs::Events_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "events[]" << std::endl;
    for (size_t i = 0; i < v.events.size(); ++i)
    {
      s << indent << "  events[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::mir_msgs::Event_<ContainerAllocator> >::stream(s, indent + "    ", v.events[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIR_MSGS_MESSAGE_EVENTS_H
