// Generated by gencpp from file mir_msgs/Gpio.msg
// DO NOT EDIT!


#ifndef MIR_MSGS_MESSAGE_GPIO_H
#define MIR_MSGS_MESSAGE_GPIO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mir_msgs
{
template <class ContainerAllocator>
struct Gpio_
{
  typedef Gpio_<ContainerAllocator> Type;

  Gpio_()
    : ioport(0)
    , dat(0)  {
    }
  Gpio_(const ContainerAllocator& _alloc)
    : ioport(0)
    , dat(0)  {
  (void)_alloc;
    }



   typedef uint8_t _ioport_type;
  _ioport_type ioport;

   typedef uint8_t _dat_type;
  _dat_type dat;



  enum {
    POWERBOARD_GPIO = 0u,
    POWERBOARD_RESET_SWITCH_LED = 1u,
    PENDANT_INPUT = 5u,
    AUTO_MODE_SWITCH = 10u,
    MANUAL_MODE_SWITCH = 11u,
  };


  typedef boost::shared_ptr< ::mir_msgs::Gpio_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mir_msgs::Gpio_<ContainerAllocator> const> ConstPtr;

}; // struct Gpio_

typedef ::mir_msgs::Gpio_<std::allocator<void> > Gpio;

typedef boost::shared_ptr< ::mir_msgs::Gpio > GpioPtr;
typedef boost::shared_ptr< ::mir_msgs::Gpio const> GpioConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mir_msgs::Gpio_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mir_msgs::Gpio_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mir_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'mir_msgs': ['/home/ros/MiR_ws/src/mir_robot/mir_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mir_msgs::Gpio_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mir_msgs::Gpio_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mir_msgs::Gpio_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mir_msgs::Gpio_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mir_msgs::Gpio_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mir_msgs::Gpio_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mir_msgs::Gpio_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9ea786c6c62a8d8cc7b65489f086f3d3";
  }

  static const char* value(const ::mir_msgs::Gpio_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9ea786c6c62a8d8cULL;
  static const uint64_t static_value2 = 0xc7b65489f086f3d3ULL;
};

template<class ContainerAllocator>
struct DataType< ::mir_msgs::Gpio_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mir_msgs/Gpio";
  }

  static const char* value(const ::mir_msgs::Gpio_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mir_msgs::Gpio_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 POWERBOARD_GPIO = 0\n\
uint8 POWERBOARD_RESET_SWITCH_LED = 1\n\
uint8 PENDANT_INPUT = 5\n\
uint8 AUTO_MODE_SWITCH = 10\n\
uint8 MANUAL_MODE_SWITCH = 11\n\
\n\
uint8 ioport\n\
uint8 dat\n\
";
  }

  static const char* value(const ::mir_msgs::Gpio_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mir_msgs::Gpio_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ioport);
      stream.next(m.dat);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Gpio_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mir_msgs::Gpio_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mir_msgs::Gpio_<ContainerAllocator>& v)
  {
    s << indent << "ioport: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ioport);
    s << indent << "dat: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dat);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIR_MSGS_MESSAGE_GPIO_H
