// Generated by gencpp from file mir_msgs/ResourcesState.msg
// DO NOT EDIT!


#ifndef MIR_MSGS_MESSAGE_RESOURCESSTATE_H
#define MIR_MSGS_MESSAGE_RESOURCESSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <mir_msgs/ResourceState.h>

namespace mir_msgs
{
template <class ContainerAllocator>
struct ResourcesState_
{
  typedef ResourcesState_<ContainerAllocator> Type;

  ResourcesState_()
    : header()
    , resources()  {
    }
  ResourcesState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , resources(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::mir_msgs::ResourceState_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::mir_msgs::ResourceState_<ContainerAllocator> >::other >  _resources_type;
  _resources_type resources;





  typedef boost::shared_ptr< ::mir_msgs::ResourcesState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mir_msgs::ResourcesState_<ContainerAllocator> const> ConstPtr;

}; // struct ResourcesState_

typedef ::mir_msgs::ResourcesState_<std::allocator<void> > ResourcesState;

typedef boost::shared_ptr< ::mir_msgs::ResourcesState > ResourcesStatePtr;
typedef boost::shared_ptr< ::mir_msgs::ResourcesState const> ResourcesStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mir_msgs::ResourcesState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mir_msgs::ResourcesState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mir_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'mir_msgs': ['/home/ros/MiR_ws/src/mir_robot/mir_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mir_msgs::ResourcesState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mir_msgs::ResourcesState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mir_msgs::ResourcesState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mir_msgs::ResourcesState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mir_msgs::ResourcesState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mir_msgs::ResourcesState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mir_msgs::ResourcesState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2e0263c09697d545680f9e07fbd8dd7e";
  }

  static const char* value(const ::mir_msgs::ResourcesState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2e0263c09697d545ULL;
  static const uint64_t static_value2 = 0x680f9e07fbd8dd7eULL;
};

template<class ContainerAllocator>
struct DataType< ::mir_msgs::ResourcesState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mir_msgs/ResourcesState";
  }

  static const char* value(const ::mir_msgs::ResourcesState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mir_msgs::ResourcesState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
ResourceState[] resources\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: mir_msgs/ResourceState\n\
string[] assigned # A token that is true whenever the resource is busy.\n\
uint32 ROBOT_POSITION=0 \n\
uint32 STAGING_POSITION=1\n\
uint32 CHARGING_STATION=2\n\
uint32 AREA=3\n\
uint32 type # The resource type\n\
uint32 path_idx # The index from the global path in which the robot gets into the position\n\
float32 distance # The distance from the robot to the resource\n\
geometry_msgs/Point collision_point # The collision point with the resource \n\
string[] queue # The queue for a resource. It's a list of robots ips.\n\
string name # The name of the resource\n\
string guid # The guid of the resource\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::mir_msgs::ResourcesState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mir_msgs::ResourcesState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.resources);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResourcesState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mir_msgs::ResourcesState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mir_msgs::ResourcesState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "resources[]" << std::endl;
    for (size_t i = 0; i < v.resources.size(); ++i)
    {
      s << indent << "  resources[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::mir_msgs::ResourceState_<ContainerAllocator> >::stream(s, indent + "    ", v.resources[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIR_MSGS_MESSAGE_RESOURCESSTATE_H
