; Auto-generated. Do not edit!


(cl:in-package mir_actions-msg)


;//! \htmlinclude RelativeMoveResult.msg.html

(cl:defclass <RelativeMoveResult> (roslisp-msg-protocol:ros-message)
  ((end_state
    :reader end_state
    :initarg :end_state
    :type cl:fixnum
    :initform 0)
   (end_pose
    :reader end_pose
    :initarg :end_pose
    :type geometry_msgs-msg:PoseStamped
    :initform (cl:make-instance 'geometry_msgs-msg:PoseStamped)))
)

(cl:defclass RelativeMoveResult (<RelativeMoveResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RelativeMoveResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RelativeMoveResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name mir_actions-msg:<RelativeMoveResult> is deprecated: use mir_actions-msg:RelativeMoveResult instead.")))

(cl:ensure-generic-function 'end_state-val :lambda-list '(m))
(cl:defmethod end_state-val ((m <RelativeMoveResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader mir_actions-msg:end_state-val is deprecated.  Use mir_actions-msg:end_state instead.")
  (end_state m))

(cl:ensure-generic-function 'end_pose-val :lambda-list '(m))
(cl:defmethod end_pose-val ((m <RelativeMoveResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader mir_actions-msg:end_pose-val is deprecated.  Use mir_actions-msg:end_pose instead.")
  (end_pose m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<RelativeMoveResult>)))
    "Constants for message type '<RelativeMoveResult>"
  '((:UNDEFINED . 0)
    (:GOAL_REACHED . 1)
    (:FAILED_TIMEOUT . 2)
    (:FAILED_COLLISION . 3)
    (:INVALID_GOAL . 4))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'RelativeMoveResult)))
    "Constants for message type 'RelativeMoveResult"
  '((:UNDEFINED . 0)
    (:GOAL_REACHED . 1)
    (:FAILED_TIMEOUT . 2)
    (:FAILED_COLLISION . 3)
    (:INVALID_GOAL . 4))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RelativeMoveResult>) ostream)
  "Serializes a message object of type '<RelativeMoveResult>"
  (cl:let* ((signed (cl:slot-value msg 'end_state)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 65536) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    )
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'end_pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RelativeMoveResult>) istream)
  "Deserializes a message object of type '<RelativeMoveResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'end_state) (cl:if (cl:< unsigned 32768) unsigned (cl:- unsigned 65536))))
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'end_pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RelativeMoveResult>)))
  "Returns string type for a message object of type '<RelativeMoveResult>"
  "mir_actions/RelativeMoveResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RelativeMoveResult)))
  "Returns string type for a message object of type 'RelativeMoveResult"
  "mir_actions/RelativeMoveResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RelativeMoveResult>)))
  "Returns md5sum for a message object of type '<RelativeMoveResult>"
  "3ab76f998827a292a12dfe9047344676")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RelativeMoveResult)))
  "Returns md5sum for a message object of type 'RelativeMoveResult"
  "3ab76f998827a292a12dfe9047344676")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RelativeMoveResult>)))
  "Returns full string definition for message of type '<RelativeMoveResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int16 UNDEFINED = 0~%int16 GOAL_REACHED = 1~%int16 FAILED_TIMEOUT = 2~%int16 FAILED_COLLISION = 3~%int16 INVALID_GOAL = 4~%int16 end_state~%geometry_msgs/PoseStamped end_pose~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RelativeMoveResult)))
  "Returns full string definition for message of type 'RelativeMoveResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int16 UNDEFINED = 0~%int16 GOAL_REACHED = 1~%int16 FAILED_TIMEOUT = 2~%int16 FAILED_COLLISION = 3~%int16 INVALID_GOAL = 4~%int16 end_state~%geometry_msgs/PoseStamped end_pose~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RelativeMoveResult>))
  (cl:+ 0
     2
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'end_pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RelativeMoveResult>))
  "Converts a ROS message object to a list"
  (cl:list 'RelativeMoveResult
    (cl:cons ':end_state (end_state msg))
    (cl:cons ':end_pose (end_pose msg))
))
