(cl:in-package mir_msgs-msg)
(cl:export '(IS_CONNECTED-VAL
          IS_CONNECTED
          IS_FIRMWARE_OK-VAL
          IS_FIRMWARE_OK
          FIRMWARE_VERSION-VAL
          FIRMWARE_VERSION
          IN_PROTECTIVE_STOP-VAL
          IN_PROTECTIVE_STOP
          IN_EMERGENCY_STOP-VAL
          IN_EMERGENCY_STOP
          STO_FEEDBACK-VAL
          STO_FEEDBACK
          IS_RESTART_REQUIRED-VAL
          IS_RESTART_REQUIRED
          IS_SAFETY_MUTED-VAL
          IS_SAFETY_MUTED
          IS_LIMITED_SPEED_ACTIVE-VAL
          IS_LIMITED_SPEED_ACTIVE
          IN_SLEEP_MODE-VAL
          IN_SLEEP_MODE
          IN_MANUAL_MODE-VAL
          IN_MANUAL_MODE
          IS_MANUAL_MODE_RESTART_REQUIRED-VAL
          IS_MANUAL_MODE_RESTART_REQUIRED
))