(cl:in-package mir_msgs-msg)
(cl:export '(CHARGING_RELAY-VAL
          CHARGING_RELAY
          CHARGING_CURRENT-VAL
          CHARGING_CURRENT
          CHARGING_CURRENT_RAW-VAL
          CHARGING_CURRENT_RAW
          LAST_TIME_CURRENT-VAL
          LAST_TIME_CURRENT
          CHARGING_VOLTAGE-VAL
          CHARGING_VOLTAGE
          CHARGING_VOLTAGE_RAW-VAL
          CHARGING_VOLTAGE_RAW
          IS_VOLTAGE_LOW-VAL
          IS_VOLTAGE_LOW
          LAST_TIME_VOLTAGE-VAL
          LAST_TIME_VOLTAGE
))